# Generated by Django 5.2.12 on 2026-04-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rarity',
            options={'verbose_name_plural': 'Rarities'},
        ),
    ]
