# Generated by Django 6.0.4 on 2026-04-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_rarity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='spritesheet',
            field=models.ImageField(default=None, upload_to='cards/spritesheets/'),
            preserve_default=False,
        ),
    ]
