# Generated by Django 6.0.4 on 2026-04-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_card_spritesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='base_move_energy',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='base_move_energy_gain',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='defense',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='health',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
