# Generated by Django 6.0.4 on 2026-04-25 00:57

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_card_base_move_energy_card_base_move_energy_gain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='spritesheet',
        ),
        migrations.CreateModel(
            name='CardSprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=game.models.card_sprite_upload_to)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
            ],
        ),
    ]
