# Generated by Django 6.0.4 on 2026-04-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_card_spritesheet_cardsprite'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='desperation',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
