# Generated by Django 6.0.4 on 2026-04-25 01:49

import django.contrib.postgres.fields
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_card_desperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sprite', models.ImageField(upload_to=game.models.move_sprite_upload_to)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('damage', models.PositiveIntegerField(blank=True, null=True)),
                ('self_defense_multipler', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('self_attack_multipler', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('self_move_energy_multipler', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('self_move_energy_gain_multipler', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('self_desperation_multipler', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('self_defense_scalar_boost', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('self_attack_scalar_boost', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('self_move_energy_scalar_boost', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('self_move_energy_gain_scalar_boost', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('self_poison', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('self_prevent_move', models.PositiveIntegerField(blank=True, null=True)),
                ('enemy_defense_multiplier', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('enemy_attack_multiplier', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('enemy_move_energy_multiplier', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('enemy_move_energy_gain_multiplier', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('enemy_desperation_multiplier', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('enemy_defense_scalar_boost', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('enemy_attack_scalar_boost', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('enemy_move_energy_scalar_boost', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('enemy_move_energy_gain_scalar_boost', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('enemy_desperation_scalar_boost', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('enemy_poison', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='desperation',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='card',
            name='moves',
            field=models.ManyToManyField(to='game.move'),
        ),
    ]
