# Generated by Django 6.0.4 on 2026-04-25 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_move_alter_card_desperation_card_moves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='moves',
        ),
        migrations.CreateModel(
            name='CardMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.move')),
            ],
        ),
    ]
